services:
  api:
    build: . # Constr칩i a imagem a partir do Dockerfile na raiz do projeto
    conteiner_name: devops # Nome do Container
    ports:
      - "8000:8000" # Mapeia a porta 8000 do Dockerfile com EXPOSE 8000 do container
    volumes:
      - .:/app # Monta o diret칩rio atual (onde est치 seu c칩digo) em /app dentro do container.